name: Quality assurance

on:
  - push
  - workflow_dispatch

env:
  PNPM_VERSION: '8.13.1'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: Check code style
        run: pnpm lint
      - name: Run tests
        run: pnpm test